/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services.index'
import { Route as AuthenticatedProposalsIndexRouteImport } from './routes/_authenticated/proposals.index'
import { Route as AuthenticatedServicesNewRouteImport } from './routes/_authenticated/services.new'
import { Route as AuthenticatedServicesIdRouteImport } from './routes/_authenticated/services.$id'
import { Route as AuthenticatedProposalsNewRouteImport } from './routes/_authenticated/proposals.new'
import { Route as AuthenticatedProposalsIdRouteImport } from './routes/_authenticated/proposals.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedProposalsIdPreviewRouteImport } from './routes/_authenticated/proposals.$id_.preview'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIndexRoute =
  AuthenticatedProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesNewRoute =
  AuthenticatedServicesNewRouteImport.update({
    id: '/services/new',
    path: '/services/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesIdRoute = AuthenticatedServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProposalsNewRoute =
  AuthenticatedProposalsNewRouteImport.update({
    id: '/proposals/new',
    path: '/proposals/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIdRoute =
  AuthenticatedProposalsIdRouteImport.update({
    id: '/proposals/$id',
    path: '/proposals/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProposalsIdPreviewRoute =
  AuthenticatedProposalsIdPreviewRouteImport.update({
    id: '/proposals/$id_/preview',
    path: '/proposals/$id/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/services/$id': typeof AuthenticatedServicesIdRoute
  '/services/new': typeof AuthenticatedServicesNewRoute
  '/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/services/': typeof AuthenticatedServicesIndexRoute
  '/proposals/$id/preview': typeof AuthenticatedProposalsIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/services/$id': typeof AuthenticatedServicesIdRoute
  '/services/new': typeof AuthenticatedServicesNewRoute
  '/proposals': typeof AuthenticatedProposalsIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/proposals/$id/preview': typeof AuthenticatedProposalsIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/_authenticated/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/_authenticated/services/$id': typeof AuthenticatedServicesIdRoute
  '/_authenticated/services/new': typeof AuthenticatedServicesNewRoute
  '/_authenticated/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/proposals/$id_/preview': typeof AuthenticatedProposalsIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/users'
    | '/proposals/$id'
    | '/proposals/new'
    | '/services/$id'
    | '/services/new'
    | '/proposals/'
    | '/services/'
    | '/proposals/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/users'
    | '/proposals/$id'
    | '/proposals/new'
    | '/services/$id'
    | '/services/new'
    | '/proposals'
    | '/services'
    | '/proposals/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/users'
    | '/_authenticated/proposals/$id'
    | '/_authenticated/proposals/new'
    | '/_authenticated/services/$id'
    | '/_authenticated/services/new'
    | '/_authenticated/proposals/'
    | '/_authenticated/services/'
    | '/_authenticated/proposals/$id_/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/': {
      id: '/_authenticated/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AuthenticatedProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/new': {
      id: '/_authenticated/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof AuthenticatedServicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/$id': {
      id: '/_authenticated/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AuthenticatedServicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/new': {
      id: '/_authenticated/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AuthenticatedProposalsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/$id': {
      id: '/_authenticated/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof AuthenticatedProposalsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/$id_/preview': {
      id: '/_authenticated/proposals/$id_/preview'
      path: '/proposals/$id/preview'
      fullPath: '/proposals/$id/preview'
      preLoaderRoute: typeof AuthenticatedProposalsIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedProposalsIdRoute: typeof AuthenticatedProposalsIdRoute
  AuthenticatedProposalsNewRoute: typeof AuthenticatedProposalsNewRoute
  AuthenticatedServicesIdRoute: typeof AuthenticatedServicesIdRoute
  AuthenticatedServicesNewRoute: typeof AuthenticatedServicesNewRoute
  AuthenticatedProposalsIndexRoute: typeof AuthenticatedProposalsIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedProposalsIdPreviewRoute: typeof AuthenticatedProposalsIdPreviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedProposalsIdRoute: AuthenticatedProposalsIdRoute,
  AuthenticatedProposalsNewRoute: AuthenticatedProposalsNewRoute,
  AuthenticatedServicesIdRoute: AuthenticatedServicesIdRoute,
  AuthenticatedServicesNewRoute: AuthenticatedServicesNewRoute,
  AuthenticatedProposalsIndexRoute: AuthenticatedProposalsIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedProposalsIdPreviewRoute: AuthenticatedProposalsIdPreviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
