/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTwoPageProposalsIndexRouteImport } from './routes/_authenticated/two-page-proposals.index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services.index'
import { Route as AuthenticatedProposalsIndexRouteImport } from './routes/_authenticated/proposals.index'
import { Route as AuthenticatedTwoPageProposalsNewRouteImport } from './routes/_authenticated/two-page-proposals.new'
import { Route as AuthenticatedTwoPageProposalsIdRouteImport } from './routes/_authenticated/two-page-proposals.$id'
import { Route as AuthenticatedServicesNewRouteImport } from './routes/_authenticated/services.new'
import { Route as AuthenticatedServicesIdRouteImport } from './routes/_authenticated/services.$id'
import { Route as AuthenticatedProposalsNewRouteImport } from './routes/_authenticated/proposals.new'
import { Route as AuthenticatedProposalsIdRouteImport } from './routes/_authenticated/proposals.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAccountPasswordRouteImport } from './routes/_authenticated/account.password'
import { Route as AuthenticatedTwoPageProposalsIdPreviewRouteImport } from './routes/_authenticated/two-page-proposals.$id_.preview'
import { Route as AuthenticatedProposalsIdPreviewRouteImport } from './routes/_authenticated/proposals.$id_.preview'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTwoPageProposalsIndexRoute =
  AuthenticatedTwoPageProposalsIndexRouteImport.update({
    id: '/two-page-proposals/',
    path: '/two-page-proposals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIndexRoute =
  AuthenticatedProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTwoPageProposalsNewRoute =
  AuthenticatedTwoPageProposalsNewRouteImport.update({
    id: '/two-page-proposals/new',
    path: '/two-page-proposals/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTwoPageProposalsIdRoute =
  AuthenticatedTwoPageProposalsIdRouteImport.update({
    id: '/two-page-proposals/$id',
    path: '/two-page-proposals/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesNewRoute =
  AuthenticatedServicesNewRouteImport.update({
    id: '/services/new',
    path: '/services/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesIdRoute = AuthenticatedServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProposalsNewRoute =
  AuthenticatedProposalsNewRouteImport.update({
    id: '/proposals/new',
    path: '/proposals/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIdRoute =
  AuthenticatedProposalsIdRouteImport.update({
    id: '/proposals/$id',
    path: '/proposals/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountPasswordRoute =
  AuthenticatedAccountPasswordRouteImport.update({
    id: '/account/password',
    path: '/account/password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTwoPageProposalsIdPreviewRoute =
  AuthenticatedTwoPageProposalsIdPreviewRouteImport.update({
    id: '/two-page-proposals/$id_/preview',
    path: '/two-page-proposals/$id/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIdPreviewRoute =
  AuthenticatedProposalsIdPreviewRouteImport.update({
    id: '/proposals/$id_/preview',
    path: '/proposals/$id/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/services/$id': typeof AuthenticatedServicesIdRoute
  '/services/new': typeof AuthenticatedServicesNewRoute
  '/two-page-proposals/$id': typeof AuthenticatedTwoPageProposalsIdRoute
  '/two-page-proposals/new': typeof AuthenticatedTwoPageProposalsNewRoute
  '/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/services/': typeof AuthenticatedServicesIndexRoute
  '/two-page-proposals/': typeof AuthenticatedTwoPageProposalsIndexRoute
  '/proposals/$id/preview': typeof AuthenticatedProposalsIdPreviewRoute
  '/two-page-proposals/$id/preview': typeof AuthenticatedTwoPageProposalsIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth': typeof AuthIndexRoute
  '/account/password': typeof AuthenticatedAccountPasswordRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/services/$id': typeof AuthenticatedServicesIdRoute
  '/services/new': typeof AuthenticatedServicesNewRoute
  '/two-page-proposals/$id': typeof AuthenticatedTwoPageProposalsIdRoute
  '/two-page-proposals/new': typeof AuthenticatedTwoPageProposalsNewRoute
  '/proposals': typeof AuthenticatedProposalsIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/two-page-proposals': typeof AuthenticatedTwoPageProposalsIndexRoute
  '/proposals/$id/preview': typeof AuthenticatedProposalsIdPreviewRoute
  '/two-page-proposals/$id/preview': typeof AuthenticatedTwoPageProposalsIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/account/password': typeof AuthenticatedAccountPasswordRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/proposals/$id': typeof AuthenticatedProposalsIdRoute
  '/_authenticated/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/_authenticated/services/$id': typeof AuthenticatedServicesIdRoute
  '/_authenticated/services/new': typeof AuthenticatedServicesNewRoute
  '/_authenticated/two-page-proposals/$id': typeof AuthenticatedTwoPageProposalsIdRoute
  '/_authenticated/two-page-proposals/new': typeof AuthenticatedTwoPageProposalsNewRoute
  '/_authenticated/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/two-page-proposals/': typeof AuthenticatedTwoPageProposalsIndexRoute
  '/_authenticated/proposals/$id_/preview': typeof AuthenticatedProposalsIdPreviewRoute
  '/_authenticated/two-page-proposals/$id_/preview': typeof AuthenticatedTwoPageProposalsIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/'
    | '/account/password'
    | '/admin/users'
    | '/proposals/$id'
    | '/proposals/new'
    | '/services/$id'
    | '/services/new'
    | '/two-page-proposals/$id'
    | '/two-page-proposals/new'
    | '/proposals/'
    | '/services/'
    | '/two-page-proposals/'
    | '/proposals/$id/preview'
    | '/two-page-proposals/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth'
    | '/account/password'
    | '/admin/users'
    | '/proposals/$id'
    | '/proposals/new'
    | '/services/$id'
    | '/services/new'
    | '/two-page-proposals/$id'
    | '/two-page-proposals/new'
    | '/proposals'
    | '/services'
    | '/two-page-proposals'
    | '/proposals/$id/preview'
    | '/two-page-proposals/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/'
    | '/_authenticated/account/password'
    | '/_authenticated/admin/users'
    | '/_authenticated/proposals/$id'
    | '/_authenticated/proposals/new'
    | '/_authenticated/services/$id'
    | '/_authenticated/services/new'
    | '/_authenticated/two-page-proposals/$id'
    | '/_authenticated/two-page-proposals/new'
    | '/_authenticated/proposals/'
    | '/_authenticated/services/'
    | '/_authenticated/two-page-proposals/'
    | '/_authenticated/proposals/$id_/preview'
    | '/_authenticated/two-page-proposals/$id_/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/two-page-proposals/': {
      id: '/_authenticated/two-page-proposals/'
      path: '/two-page-proposals'
      fullPath: '/two-page-proposals/'
      preLoaderRoute: typeof AuthenticatedTwoPageProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/': {
      id: '/_authenticated/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AuthenticatedProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/two-page-proposals/new': {
      id: '/_authenticated/two-page-proposals/new'
      path: '/two-page-proposals/new'
      fullPath: '/two-page-proposals/new'
      preLoaderRoute: typeof AuthenticatedTwoPageProposalsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/two-page-proposals/$id': {
      id: '/_authenticated/two-page-proposals/$id'
      path: '/two-page-proposals/$id'
      fullPath: '/two-page-proposals/$id'
      preLoaderRoute: typeof AuthenticatedTwoPageProposalsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/new': {
      id: '/_authenticated/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof AuthenticatedServicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/$id': {
      id: '/_authenticated/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AuthenticatedServicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/new': {
      id: '/_authenticated/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AuthenticatedProposalsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/$id': {
      id: '/_authenticated/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof AuthenticatedProposalsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/password': {
      id: '/_authenticated/account/password'
      path: '/account/password'
      fullPath: '/account/password'
      preLoaderRoute: typeof AuthenticatedAccountPasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/two-page-proposals/$id_/preview': {
      id: '/_authenticated/two-page-proposals/$id_/preview'
      path: '/two-page-proposals/$id/preview'
      fullPath: '/two-page-proposals/$id/preview'
      preLoaderRoute: typeof AuthenticatedTwoPageProposalsIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/$id_/preview': {
      id: '/_authenticated/proposals/$id_/preview'
      path: '/proposals/$id/preview'
      fullPath: '/proposals/$id/preview'
      preLoaderRoute: typeof AuthenticatedProposalsIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAccountPasswordRoute: typeof AuthenticatedAccountPasswordRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedProposalsIdRoute: typeof AuthenticatedProposalsIdRoute
  AuthenticatedProposalsNewRoute: typeof AuthenticatedProposalsNewRoute
  AuthenticatedServicesIdRoute: typeof AuthenticatedServicesIdRoute
  AuthenticatedServicesNewRoute: typeof AuthenticatedServicesNewRoute
  AuthenticatedTwoPageProposalsIdRoute: typeof AuthenticatedTwoPageProposalsIdRoute
  AuthenticatedTwoPageProposalsNewRoute: typeof AuthenticatedTwoPageProposalsNewRoute
  AuthenticatedProposalsIndexRoute: typeof AuthenticatedProposalsIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedTwoPageProposalsIndexRoute: typeof AuthenticatedTwoPageProposalsIndexRoute
  AuthenticatedProposalsIdPreviewRoute: typeof AuthenticatedProposalsIdPreviewRoute
  AuthenticatedTwoPageProposalsIdPreviewRoute: typeof AuthenticatedTwoPageProposalsIdPreviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAccountPasswordRoute: AuthenticatedAccountPasswordRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedProposalsIdRoute: AuthenticatedProposalsIdRoute,
  AuthenticatedProposalsNewRoute: AuthenticatedProposalsNewRoute,
  AuthenticatedServicesIdRoute: AuthenticatedServicesIdRoute,
  AuthenticatedServicesNewRoute: AuthenticatedServicesNewRoute,
  AuthenticatedTwoPageProposalsIdRoute: AuthenticatedTwoPageProposalsIdRoute,
  AuthenticatedTwoPageProposalsNewRoute: AuthenticatedTwoPageProposalsNewRoute,
  AuthenticatedProposalsIndexRoute: AuthenticatedProposalsIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedTwoPageProposalsIndexRoute:
    AuthenticatedTwoPageProposalsIndexRoute,
  AuthenticatedProposalsIdPreviewRoute: AuthenticatedProposalsIdPreviewRoute,
  AuthenticatedTwoPageProposalsIdPreviewRoute:
    AuthenticatedTwoPageProposalsIdPreviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
